### ISSUE TITLE
Match URL more better

### ISSUE THREAD

**Issue by valrus** [valrus/mefi-comment-colors#2]
Per <a href="http://metatalk.metafilter.com/24039/Color-Comments-By-User#1237823">tonycpsu</a>:

> `// @include http://www.metafilter.com/*`
> should be something like:
> `// @include        /^https?://(.*\.)?metafilter\.com/`
> for those of us who use the SSL site. Of course Greasemonkey can set it to run other sites, but the default should probably include https.

**Comment by roukaour** [comment]
`@include *://*.metafilter.com/*` should work.
